name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install yarn
        run: npm install -g yarn

      - name: Install app dependencies
        run: yarn setup

      - name: Configure the platform
        continue-on-error: true
        run: yarn clean

      - name: Build Android dev apk
        run: yarn build android paid dev

      - name: Build Android prod aab
        run: yarn build android paid prod

      - name: Upload dev APK
        uses: actions/upload-artifact@v3
        with:
          name: app-dev
          path: ./*debug.apk

      - name: Remove dev apk locally (for compatability)
        run: rm ./*debug.apk
      
      - name: Upload release apk
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ./*.apk

      - name: File Tree
        run: tree ./
